### ISSUE TITLE
Drivers works on model Asus Zenbook UX362-FA too

### ISSUE THREAD

**Issue by xnosek00** [mohamed-badaoui/ux433-touchpad-numpad#15]
Hi,

  can you add line to readme, that your driver works on Asus Zenbook UX362-FA? 

  It's variant without % symbols: https://github.com/mohamed-badaoui/ux433-touchpad-numpad/blob/main/Asus-ZenBook-UX433FA.jpg

  I can confirm, that i realy works on my model. 

  Thank you.

Petr

**Comment by mohamed-badaoui** [comment]
Hi Petr,

Ok done.

Thank you for your feedback!
