### ISSUE TITLE
estimated battery time display asus zenbook ux434fa os 5.8

### ISSUE THREAD

**Issue by cedrichappy** [mohamed-badaoui/ux433-touchpad-numpad#5]
hi mohamed,

I have a question about the display of the estimated time remaining of the battery because I have a problem, the battery works well but the estimated time remaining changes each time I look would you have an idea to fix this problem?

**Comment by mohamed-badaoui** [comment]
Hi Cedric,

Unfortunately I have no idea, never see that kind of issue. 
Sorry.
