### ISSUE TITLE
Asus Zenbook S UX393 support (with %)

### ISSUE THREAD

**Issue by angryziber** [mohamed-badaoui/ux433-touchpad-numpad#6]
On my laptop the script says that touchpad is not found. The correct device in `/proc/bus/input/devices` is:

I: Bus=0018 Vendor=04f3 Product=3134 Version=0100
N: Name="ASUE140A:00 04F3:3134 Touchpad"

However, the script looks for `if touchpad_detected == 0 and "Name=\"ELAN" in line and "Touchpad" in line:`, but my device name starts with ASUE. I have other ELAN devices as well, but the one above works to switch the numpad on.

Can the script just look for "Touchpad" without the "ELAN"?

**Comment by mohamed-badaoui** [comment]
Hi,
When you run install.sh, please make sure you answer Y for the first question while you ve a keyboard layout with % symbol.
Install.ah should print 
Your numpad has % and = symbols.

Otherwise can you give us the complete return of install.sh?
